name: Validador de Tipos (MyPy)
run-name: Rodando MyPy
on:
  push:
    branches:
      - main
    paths:
      - source/**
      - tests/**
      - configs/mypy.ini
  workflow_dispatch:
jobs:
    mypy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Configurar Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11
            - name: Configurar Severino
              run: make setup
            - name: Rodar MyPY
              run: make mypy
