name: Testes
run-name: Rodando os testes unitários
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
    testes:
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Configurar Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11
            - name: Configurar Severino
              run: make setup
            - name: Rodar os testes & coletar informacoes de coverage
              uses: paambaati/codeclimate-action@v4.0.0
              with:
                coverageCommand: make pytest
                debug: true
